### ISSUE TITLE
Error Occurs When Importing N/compress and N/dataset Modules

### ISSUE THREAD

**Issue by tomo-local** [acdvs/eslint-plugin-suitescript#11]
**Is your feature request related to a problem? Please describe.**
When importing the N/compress module, an error occurs. Additionally, N/dataset is also not supported. I will provide detailed explanations about this issue.

**Describe the solution you'd like**
I would like the N/compress and N/dataset modules to be integrated correctly into eslint-plugin-suitescript and fixed to prevent errors from occurring.

**Describe alternatives you've considered**
As an alternative solution to resolve the issue, I have considered whether any specific procedures or configurations are required to work around the problem in the current code, but I couldn't find a solution.

**Comment by tomo-local** [comment]
@acdvs 
Is it acceptable for me to address this issue on my end?

**Comment by acdvs** [comment]
@tomo-local Not sure when I'll get around to adding these modules, but you're welcome to submit a PR.

**Comment by tomo-local** [comment]
@acdvs 
I created the pr. Could you please confirm?
