### ISSUE TITLE
Missing Script Type "plugintypeimpl"

### ISSUE THREAD

**Issue by agerber123** [acdvs/eslint-plugin-suitescript#15]
**Describe the bug**
I get an error message because the script type “plugintypeimpl” is missing in the list.

However, it is a valid type:

https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_3976784634.html#bridgehead_4573723266

**To Reproduce**
- Create a file with "@NScriptType plugintypeimpl"
- run eslint

**Expected behavior**
no error with script type “plugintypeimpl”

**Node version**
18

**ESLint version**
8.57.0

![Bildschirmfoto 2024-05-29 um 10 32 05](https://github.com/acdvs/eslint-plugin-suitescript/assets/124154789/eb24154c-5718-4de1-ba97-e0db2f36a147)

**Comment by acdvs** [comment]
Fixed with 2965dc3.
